### ISSUE TITLE
Field name collision

### ISSUE THREAD

**Issue by tormi** [markaspot/service_request#1]
Hi Holger!

Nice to see you're converting mas components to 8.x! I tried to install SR in a site with `field_image` already in use and got this error:

> Unable to install Service Request Content Type, field.storage.node.field_image already exists in active configuration.

One way to avoid that is prefixing all SR fields with sr_ or sth, like `field_sr_image`, `field_sr_geolocation` etc.

Tormi

**Comment by markaspot** [comment]
Tormi, thanks for this issue! I still wonder why there is no condition in core to ignore a config if a storage configuration already exists. Anyway, the few modules available here are yet working only during the composer based distribution installation process. I recognize the claim to have them enabled anytime, but this not the focus of the current development. Anyway, fix coming soon.
